### ISSUE TITLE
err

### ISSUE THREAD

**Issue by cardermeister** [South-Paw/salien-script-js#1]
[TypeError: Cannot read property '                                                    accountid' of undefined](https://i.imgur.com/L9cAP2Q.png)

**Comment by South-Paw** [comment]
Looks like it was a bug where the user had never joined a `clan` in the game before so the `clan_info` key wasn't present. This should be fixed now, I've tested it on another account as well.

Thanks for the issue report and please let me know if you have any other problems 👍
