### ISSUE TITLE
Prioritize most captured planet when only medium/easy zones remain

### ISSUE THREAD

**Issue by Pankrakles** [South-Paw/salien-script-js#10]
Change it so it prioritises the planet with the closest to finishing, could use the same ETA thing used on https://mlomb.github.io/SalienBot/ . :)

**Comment by South-Paw** [comment]
I'll try get to this unless someone else beats me to it or @resir014 gets time to put it in... seems reasonably easy to do though

**Comment by South-Paw** [comment]
after #19 we can implement this easier
