### ISSUE TITLE
token Fetch Error on Heroku

### ISSUE THREAD

**Issue by DarKCroX** [South-Paw/salien-script-js#14]
![img](https://i.imgur.com/lzYGvuD.png)

**Comment by hdk5** [comment]
extra " at beginning

**Comment by DarKCroX** [comment]
Ahh
I thought need to write with quotation marks too because on README.md have one
Thanks!

**Comment by Pankrakles** [comment]
Could you help me setup heroku as well if you don't mind? not sure what to put in the procfile atm.

**Comment by hdk5** [comment]
@Pankrakles deploy to heroku button should give you already working app, you only have to provide your token

**Comment by Pankrakles** [comment]
What deploy to heroku button?
I've cloned the script, but now I cant deploy it with `git push heroku master`

**Comment by Pankrakles** [comment]
You can add me on discord, might be easier if you want to help a pleb like me :P 
Pankrakles#0338

**Comment by South-Paw** [comment]
Closing as original issue is solved, thanks @hdk5 👍
