### ISSUE TITLE
No log from heroku.

### ISSUE THREAD

**Issue by coxapy** [South-Paw/salien-script-js#21]
Empty application log. Is it supposed to be like that?

**Comment by Pankrakles** [comment]
Yes, the web page is disabled because it's not needed.
If you want to see the logs go to this url https://dashboard.heroku.com/apps/YOURAPPNAMEHERE/logs
, replacing the YOURAPPNAMEHERE with your app name which you can see at the top,or click the "more" button on the app page and click view logs.

**Comment by coxapy** [comment]
@Pankrakles It's empty there. That's why I'm asking.
