### ISSUE TITLE
How do I know if this is safe?

### ISSUE THREAD

**Issue by maculai** [South-Paw/salien-script-js#22]
I put in my token. After viewing a Reddit post, people are saying you shouldn't do that.

**Comment by Pankrakles** [comment]
The token can only be used for this game if someone were to steal it all they could do is run a script for you which in reality won't cause any damage. If you don't trust people just use the node.js script and you can check the code that its not sending it somewhere else.
TLDR - Its safe to use this script with heroku and node.js and everything else :)

**Comment by South-Paw** [comment]
@suhwoop You're welcome to read the code and look where the network calls are made - you'll find there is a fixed url they are being sent to `https://community.steam-api.com/` and that the code doesn't do anything more than it says it does (which is run the game via the steam api for you)

The update checker is not an automagic installer or anything, it simply checks npmjs for a new version and puts a log message in the console if there is (no downloads or anything there).

**At the end of the day though, anything you download from the internet at all has a risk to your PC** - if you're worried about it I can't do much to help you beyond say the above 👍
