### ISSUE TITLE
Failed to check for update

### ISSUE THREAD

**Issue by Siiper** [South-Paw/salien-script-js#25]
https://i.imgur.com/BxdxeUR.png
I really dont know what cause this, happened when there's an update and will take awhile till the system stop telling me there's an error and show me a update (and sometimes i still got an error even there's no update)

**Comment by South-Paw** [comment]
I haven't see this personally but a quick google search looks like it might be a bug in node 10 (although rare)

https://github.com/nodejs/node/issues/21088

https://github.com/vesse/node-ldapauth-fork/issues/65

can't do much about it sorry but on the bright side it won't be impacting the running of your script either.
