### ISSUE TITLE
Incorrect ETA

### ISSUE THREAD

**Issue by Jerryh001** [South-Paw/salien-script-js#26]
(I don't coding with javascript so I use C-style to describe it)

the remain time should be like
ceil( (float) REMAIN_XP / XP_EARN ) * WAIT_TIME /60

instead of just 
REMAIN_XP / XP_EARNED_THIS_TIME * WAIT_TIME / 60

while REMAIN_XP<XP_EARNED_THIS_TIME, 
ETA will be 0h 0m but obviously it is not.

though it's not a big problem

**Comment by South-Paw** [comment]
I don't understand what you mean?

Our current ETA implementation is as follows:

```
const timeRemaining = ((report.next_level_score - report.new_score) / getScoreForZone(zoneInfo)) * (this.waitTime / 60);
const hoursRemaining = Math.floor(timeRemaining / 60);
const minutesRemaining = Math.round(timeRemaining % 60);
```

https://github.com/South-Paw/salien-script-js/blob/master/src/index.js#L736

that doesn't seem to match what you're suggesting it is with `REMAIN_XP / XP_EARNED_THIS_TIME * WAIT_TIME / 60`

**Comment by Jerryh001** [comment]
I thought the way how division works on JS is same to C . I'm sorry. Please ignore what I said above.

But the issue still exist. For example: When remaining XP is 1000 and I was in a hard zone (with 2400XP)  before. ETA is 0h 0m but it actually need to play the game one more time.(That happened to me few hours ago)

**Comment by South-Paw** [comment]
that doesn't seem like a major issue but I've fixed it anyway 👍
