### ISSUE TITLE
Option to focus on a desired planet for a better chance at the giveaway

### ISSUE THREAD

**Issue by joavd** [South-Paw/salien-script-js#30]
In version 0.0.12 there was an option (`--planet xx`) to focus on a desired planet. Can you guys bring it back for the next version?
This option is helpful for some people who want to focus on a specific planet to have a better chance at the giveaway.

**Comment by Pankrakles** [comment]
You could use the heroku version which has the option to, [here](https://github.com/South-Paw/salien-script-js#heroku-configuration)
