### ISSUE TITLE
Since today I’m in a loop of leaving planet. 

### ISSUE THREAD

**Issue by Marc3lX** [South-Paw/salien-script-js#32]
All I get is: `>> Leaving planet 25, because we want to be on 30`.

**Comment by South-Paw** [comment]
You'll need to provide more info for us to help as just that one line isn't enough

* Version of the script are you running
* How you are running it (command line, heroku, docker...)
* More logging output
* Have you also got the game open in a browser or two scripts running?
* Have you restarted you script?

**Comment by Marc3lX** [comment]
First of all it works normally again for me. (Started it a few hours later and it worked again)

- Version of the script are you running
Node.js version: v10.4.1
Script version: 0.0.13
- How you are running it (command line, heroku, docker...)
linux command line
- More logging output
Just this in the log:
` Leaving planet 25, because we want to be on 30`
` Leaving planet 25, because we want to be on 30`
` Leaving planet 25, because we want to be on 30`
` Leaving planet 25, because we want to be on 30`
- Have you also got the game open in a browser or two scripts running?
No only one script was running atm.
- Have you restarted you script?
After a restart the problem persisted.

**Comment by South-Paw** [comment]
Think I've identified where the bug is, its not fetching the playerinfo again after leaving a game so it thinks it's still in it.
