### ISSUE TITLE
SalienScriptRestart: !! Failed to join a zone

### ISSUE THREAD

**Issue by boberson420** [South-Paw/salien-script-js#46]
I am unable to join any zone...

The script just keeps restarting and does not give me any other error. I have tried on multiple accounts but the same result. I am unable to use another computer as i only have 1.

Error: SalienScriptRestart: !! Failed to join a zone

Hopefully someone can help!

P.S. script was working fine for quite a few hours, until i got home and saw it was stuck.

**Comment by boberson420** [comment]
UPDATE: everything seems to be resolved now. Not quite to sure what caused it.
My guess is that there was one hard zone left and everyone tried to join it or it was trying to join a planet that doesn't exist.

Either way everything is working.

**Comment by sjuery** [comment]
Its a boss zone, just got added and gives a shit tonne of exp... Guess we gotta wait for script to update for the new zone.

**Comment by South-Paw** [comment]
Hi guys, I'm away for the weekend but working on a laptop to fix the script for these boss zones!

**Comment by Tosh-k1** [comment]
cannot run the script at all for over the last hour, constantly restarting, even with the newest update

**Comment by South-Paw** [comment]
FYI ... there is no new version - there hasn't been an update published to npm for 3 days on the script.

I'm about to push out a new version now.

**Comment by Tosh-k1** [comment]
ah ok, i thought the commits were like little new versions as the update was  "updating" something.   Also, thanks for doing this script, ur awesome :)

**Comment by Tosh-k1** [comment]
i figured it was the same issue since im getting the exact same error that this issue has in the title. Sorry but i thought it would be better than posting a new issue with the exact same title.

**Comment by South-Paw** [comment]
@Tosh-k1 all good man, im stressed as I'm away this weekend for work and want to get the boss bug fixed for everyone but can't properly test it and just worried.

Thanks for using the project tho, hopefully new version fixes issue 👍

**Comment by Tosh-k1** [comment]
@South-Paw i just updated to the new version and so far it works, as in no constant resetting. I guess we just wait for boss now to see what happens :)


Also, just wanted to say thanks for making the project and letting all of us use it, it really is awesome of you.

**Comment by Botanistt** [comment]
I get the exact same error even though I have updated to the latest version available.

**Comment by South-Paw** [comment]
@Botanistt pass the `-l` option so requests can be logged and copy your logs please

**Comment by South-Paw** [comment]
If someone gets back to me with a log I can do something about it, without it I don't know what the issue is - will reopen when someone throws a me a log
