### ISSUE TITLE
Boss battles

### ISSUE THREAD

**Issue by Pankrakles** [South-Paw/salien-script-js#47]
All 3 of my bots running the script all failed to join the zone of the boss every time.

> [00:28:26] >> Planet 34 has an uncaptured boss zone, selecting it
> [00:28:26] >> Selected Next Zone 18 on Planet 34 (Captured: 97.89% - Difficulty: BOSS - Easy)
> 
> [00:28:27] SalienScriptRestart: !! Failed to join a zone

People are saying to switch to do it on the browser when it comes up but is it possible to get the script working for the boss fight instead?

**Comment by lollka** [comment]
xPaw's SalienCheat just recieved update for boss games, so we are waiting for this library update.

**Comment by JonathanKA** [comment]
Great work thanks! 
how we update when it's out?

**Comment by Pankrakles** [comment]
https://github.com/South-Paw/salien-script-js#-how-to-update-the-script
I'm using xPaw's script atm because its getting boss updates
