### ISSUE TITLE
to make boss zones take as long as possible

### ISSUE THREAD

**Issue by scroat** [South-Paw/salien-script-js#58]
hi guys, reading about the place i saw someone comment that the quicker bosses are defeated, the less xp rewarded. don't know if it's true, but interesting.

anecdotally-  earlier boss zone i was in i received 600k xp, latest one 200k xp- despite both bosses starting with 100mil xp.

i wonder if there is a way to string these out?

thanks to everyone for the script.

this isn't really an issue but i didn't see anywhere else to raise the topic.

**Comment by South-Paw** [comment]
There is no way to string these things out and even I adjust this script to try do so other scripts would have to do the same to make any difference

On the bright side: the quicker the bosses are defeated, the harder the bosses get, the more xp we all get.

**Comment by scroat** [comment]
roger that :P
